name: Secrets GitHub Actions Workflow

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

      # Use a GitHub Actions secret variable in a bash shell
env: 
          WHO_TO_TRUST: ${{ secrets.DB_NAME }}
          if:  env.WHO_TO_TRUST == 'DB_NAME'
          run: echo "I know what the secret token is!"

      # Action if statement with a secret environment variable
shell: bash 
WHO_TO_TRUST: ${{ secrets.DB_USER }}
if:  env.WHO_TO_TRUST != 'TrustNobody'
run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
     if:  env.WHO_TO_TRUST == 'DB_PASSWORD'
        run: echo "I know what the secret token is!"
        
